import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";

const suite = localFont({
    src: "./fonts/SUITE-Variable.woff2",
    variable: "--font-suite",
    weight: "100 900",
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import { CounterStoreProvider } from '@/app/providers/testProvider';

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${suite.variable}  antialiased`}
        >
        <div className={"flex justify-center w-full min-h-screen "}>
            <div className={"max-w-[500px] w-full  flex flex-col relative"}>
                <div className={" w-full max-w-[500px] h-[4.5rem] flex-shrink-1 pt-3 px-3 fixed top-0 bg-white z-[1000] shadow-md overflow-x-hidden"}>
                    <div>
                        <button
                            className="flex flex-row gap-1 items-center justify-center rounded-lg px-3 py-2 font-bold text-gray-700 bg-white border-2 border-gray-200 transition hover:bg-gray-50">


                            <div className="text-lg leading-8">🗂️ 퀘스트</div>
                        </button>
                    </div>
                </div>
                <div className={"flex-grow absolute top-20 w-full"}>
                    <CounterStoreProvider>
                        {children}
                    </CounterStoreProvider>

                </div>

            </div>
        </div>

        </body>
        </html>
    );
}
